# Write your code here :-)
print("=====================")
print("    Best Friend Maker     ")
print("=====================")
print("")
print("Hi. I'm the computer")
name = input("What's your name? ")
if name == ("Creeper"):
    print(f"Aww man!")
color = input(f"Hi, {name}! What's your favorite color? ")
if color == ("lightning"):
    print(f"A charged creeper, Eh?")
print(f"No way! My favorite color is also {color}!")
movie = input("What's your favorite movie? ")
print(f"What!?! My favorite movie is also {movie}!")
game = input("Wait a minute... What is your favorite game? ")
print(f"Dude no way! My favorite game is {game}, too! ")
print(f"We like the same things, How cool is that? I think we're gonna be best friends!")